# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0buserservice\"F\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"F\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"6\n\x10LoginUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"=\n\x11LoginUserResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\"$\n\x0cTokenRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"8\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"q\n\x17TokenValidationResponse\x12!\n\x04user\x18\x01 \x01(\x0b\x32\x11.userservice.UserH\x00\x12\x11\n\x07message\x18\x02 \x01(\tH\x00\x12\x14\n\x0ctoken_status\x18\x03 \x01(\x08\x42\n\n\x08response2\x87\x02\n\x0bUserService\x12O\n\nCreateUser\x12\x1e.userservice.CreateUserRequest\x1a\x1f.userservice.CreateUserResponse\"\x00\x12S\n\x10\x41uthenticateUser\x12\x1d.userservice.LoginUserRequest\x1a\x1e.userservice.LoginUserResponse\"\x00\x12R\n\rValidateToken\x12\x19.userservice.TokenRequest\x1a$.userservice.TokenValidationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=35
  _globals['_CREATEUSERREQUEST']._serialized_end=105
  _globals['_CREATEUSERRESPONSE']._serialized_start=107
  _globals['_CREATEUSERRESPONSE']._serialized_end=177
  _globals['_LOGINUSERREQUEST']._serialized_start=179
  _globals['_LOGINUSERREQUEST']._serialized_end=233
  _globals['_LOGINUSERRESPONSE']._serialized_start=235
  _globals['_LOGINUSERRESPONSE']._serialized_end=296
  _globals['_TOKENREQUEST']._serialized_start=298
  _globals['_TOKENREQUEST']._serialized_end=334
  _globals['_USER']._serialized_start=336
  _globals['_USER']._serialized_end=392
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_start=394
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_end=507
  _globals['_USERSERVICE']._serialized_start=510
  _globals['_USERSERVICE']._serialized_end=773
# @@protoc_insertion_point(module_scope)
